auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("listing/<str:title>/", views.listing, name="listing"),
    path("categories/", views.categories, name="categories"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("add_to_watchlist/<str:title>/", views.add_to_watchlist, name="add_to_watchlist"),
    path("remove_from_watchlist/<str:title>/", views.remove_from_watchlist, name="remove_from_watchlist"),
    path("new_bid/<int:id>", views.new_bid, name="new_bid"),
    path("close_auction/<int:id>", views.close_auction, name="close_auction"),
    path("wins_bids", views.wins, name="wins"),
    path("comments/<int:id>", views.comments, name="comments"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Bid(models.Model):
    new_bid = models.DecimalField(max_digits=10, blank=True, decimal_places=2)
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} new bid: ${self.new_bid}"


class Category(models.Model):
    category_name = models.CharField(max_length=64)

    def __str__(self):
        return self.category_name
    

class Comment(models.Model):
    comment = models.CharField(max_length=180)
    comment_listing = models.ForeignKey('Listing', on_delete=models.SET_NULL, null=True, related_name="comments")
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name="commentor")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}: {self.comment}"


class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()
    imageURL = models.URLField(max_length=220, blank=True)
    current_bid = models.ForeignKey('Bid', on_delete=models.CASCADE, related_name="listing", default=0)
    is_active = models.BooleanField(default=True)
    seller = models.ForeignKey('User', on_delete=models.CASCADE, blank=True, related_name="seller")
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="category")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class User(AbstractUser):
    watchlist = models.ManyToManyField('Listing', blank=True, related_name="user_watching")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"



"""
You will also need to add additional models to this file to represent details about auction listings, bids, comments, and auction categories. 
Remember that each time you change anything in auctions/models.py, 
you’ll need to first run python manage.py makemigrations 
and then python manage.py migrate to migrate those changes to your database.
"""
"""
Models: Your application should have at least three models in addition to the User model: 
one for auction listings, one for bids, and one for comments made on auction listings. 
It’s up to you to decide what fields each model should have, and what the types of those fields should be.
"""

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import User, Listing, Category, Bid, Comment


def categories(request):
    if request.method == "GET":
        categories = Category.objects.all().order_by('category_name')
        return render(request, "auctions/categories.html", {
            "categories": categories,
        })
    else:
        selected_category_id = request.POST['selected_category']
        selected_category = Category.objects.get(pk=selected_category_id)
        category_listings = Listing.objects.filter(category=selected_category, is_active=True)
        return render(request, "auctions/index.html", {
            "listings": category_listings
        })
    

def close_auction(request, id):
    if request.method == "POST":
        listing = Listing.objects.get(pk=id)
        listing.is_active = False
        listing.save()
        return render (request, "auctions/listing.html", {
            "listing": listing,
            "message": "Auction is closed."
        })


@login_required
def comments(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            user = request.user
            listing = Listing.objects.get(pk=id)
            comment = request.POST['new_comment']
            new_comment = Comment(
                comment = comment,
                comment_listing = listing,
                user = user,
            )
            print("New comment text:", comment)
            new_comment.save()
            comments = Comment.objects.filter(comment_listing=listing).order_by('-created_at')
            # Check if the person signed in is the owner of the listing, assume not.
            userowner = False
            if user.username == listing.seller.username:
                userowner = True
            in_watchlist = False
            if listing in user.watchlist.all():
                in_watchlist = True
            # Display a winning message is the listing is closed and the user is the highest bidder.
            is_active = listing.is_active
            won = False
            if listing.current_bid.user == user and not is_active:
                won = True

            return render(request, "auctions/listing.html", {
                "listing": listing,
                "userowner": userowner,
                "in_watchlist": in_watchlist,
                "is_active": is_active,
                "won": won,
                "comments": comments,
            })



@login_required
def create_listing(request):
    if request.method == "GET":
        allCategories = Category.objects.all()
        return render(request, "auctions/create_listing.html", {
            "categories": allCategories,
        })
    else:
        if request.user.is_authenticated:
            try:
                title = request.POST['listing_title']
                description = request.POST['listing_description']
                imageURL = request.POST['listing_image_url']
                start_price = request.POST['listing_start_price']
                category_name = request.POST['listing_category']
                category = Category.objects.get(category_name=category_name)
                user = request.user
                # Price will be from creating a new Bid
                starting_bid = Bid(new_bid=float(start_price), user=user)
                starting_bid.save()
                # Create new listing
                new_listing = Listing(
                    title=title,
                    description=description,
                    imageURL=imageURL,
                    current_bid=starting_bid,
                    category=category,
                    seller=user
                )
                new_listing.save()
                return HttpResponseRedirect(reverse("auctions:index"))
            except ValueError as e:
                print(f"Value Error: {e}") 



def index(request):
        active_listings = Listing.objects.filter(is_active=True).order_by('-created_at')
        return render(request, "auctions/index.html", {
            "listings": active_listings,
        })


def listing(request, title):
    listing = Listing.objects.get(title=title)
    if request.method == "GET":
        if request.user.is_authenticated:
            user = request.user
            in_watchlist = False
            # Check if is active
            is_active = listing.is_active
            # Check if the person signed in is the owner of the listing, assume not.
            userowner = False
            if user.username == listing.seller.username:
                userowner = True

            if listing in user.watchlist.all():
                in_watchlist = True

            # Display a winning message is the listing is closed and the user is the highest bidder.
            won = False
            if listing.current_bid.user == user and not is_active:
                won = True

            # Display comments
            comments = Comment.objects.filter(comment_listing=listing).order_by('-created_at')
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "in_watchlist": in_watchlist,
                "userowner": userowner,
                "is_active": is_active,
                "won": won,
                "comments": comments,
            })
        else:
            comments = Comment.objects.filter(comment_listing=listing).order_by('-created_at')
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "comments": comments,
            })




def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


@login_required
def new_bid(request, id):
    if request.user.is_authenticated:
        user = request.user
        new_bid = float(request.POST['bid'])
        listing = Listing.objects.get(pk=id)
        is_active = listing.is_active
        comments = Comment.objects.filter(comment_listing=listing).order_by('-created_at')
        userowner = False
        if user.username == listing.seller.username:
            userowner = True
        if new_bid > listing.current_bid.new_bid:
            update_bid = Bid(user=request.user, new_bid=new_bid)
            update_bid.save()
            listing.current_bid = update_bid
            listing.save()
            return render (request, "auctions/listing.html", {
                "listing": listing,
                "is_active": is_active,
                "message": "You're the highest bidder!",
                "userowner": userowner,
                "comments": comments,
            })
        else:
            return render (request, "auctions/listing.html", {
                "listing": listing,
                "is_active": is_active,
                "message": "Enter a higher bid amount",
                "userowner": userowner,
                "comments": comments,
            })
    else:
        return render (request, "auctions/listing.html")
    
# Figure out how the hell I got bidding to work??? I have absolutely no idea.


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def watchlist(request):
    if request.user.is_authenticated:
        # Get user
        user = request.user
        # Get all items in user watchlist
        watchlistings = user.watchlist.all()
        return render(request, "auctions/watchlist.html", {
            "watchlistings": watchlistings,
        })


def add_to_watchlist(request, title):
    if request.user.is_authenticated:
        user = request.user
        listing = Listing.objects.get(title=title)
        user.watchlist.add(listing)
        return HttpResponseRedirect (reverse("auctions:listing", args=(title, )))
    

def remove_from_watchlist(request, title):
    if request.user.is_authenticated:
        user = request.user
        listing = Listing.objects.get(title=title)
        user.watchlist.remove(listing)
        return HttpResponseRedirect (reverse("auctions:listing", args=(title, )))
    

@login_required
def wins(request):
    user = request.user
    won_listings = Listing.objects.filter(is_active=False, current_bid__user=user)
    watchlistings = user.watchlist.all()

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Listing Categories</h2>

    <form action="{% url 'auctions:categories' %}" method="POST">
        {% csrf_token %}
        <ul>
            {% for category in categories %}
                <li>
                    <button type="submit" name="selected_category" value="{{ category.id }}" class="btn btn-link">{{ category }}</button>
                </li>
            {% endfor %}
        </ul>
    </form>

{% endblock %}

<!--
    Categories: 
    Users should be able to visit a page that displays a list of all listing categories. 
    Clicking on the name of any category should take the user to a page that displays all of the active listings in that category.
-->

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listing</h2>

    <form action="{% url 'auctions:create_listing' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" class="form-control" style="width: 500px" id="title" maxlength="64" name="listing_title" required><br>
        <label for="description">Description:</label><br>
        <textarea id="description" name="listing_description" required></textarea><br>
        <label for="category">Category:</label> 
        <select name="listing_category" id="category" required>
            {% for category in categories %}
                <option value="{{ category.category_name }}">{{ category.category_name }}</option>
            {% endfor %}
        </select><br>
        <label for="image_url">Image URL (optional):</label>
        <input type="text" id="image_url" name="listing_image_url"><br>
        <label for="starting_price">Starting bid:</label>
        <input type="number" id="starting_price" min="0" step="any" placeholder="0.00" name="listing_start_price" required>
        <button class="btn btn-primary" type="submit">Post Listing</button>
    </form>
{% endblock %}



<!--
    Create Listing: 
    Users should be able to visit a page to create a new listing. 
    They should be able to specify a title for the listing,
     a text-based description, 
     and what the starting bid should be. 
     
     Users should also optionally be able to provide a URL for an image for the listing and/or a category 
     (e.g. Fashion, Toys, Electronics, Home, etc.).
-->

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <h6><a href="{% url 'auctions:categories' %}">Categories</a><br></h6>
    
        <ul>
            {% for listing in listings %}
                <li>
                    <a href="{% url 'auctions:listing' title=listing.title %}" class="btn btn-link">{{ listing.title }}</a><br>
                    Description: {{ listing.description }}<br>
                    Current Price: ${{ listing.current_bid.new_bid }}<br>
                    Highest bidder: {{ listing.current_bid.user.username }}<br>
                    <a href="{% url 'auctions:listing' title=listing.title %}">
                        <img src="{{ listing.imageURL }}" style="max-width: 250px;">
                    </a><br>
                    Seller: {{ listing.seller.username }}
                </li><br>
            {% empty %}
                <li>No Listings.</li>
            {% endfor %}
        </ul>
{% endblock %}



<!--
    Active Listings Page: 
    The default route of your web application should let users view all of the currently active auction listings. 
    For each active listing, this page should display (at minimum) 
    the title, description, current price, and photo (if one exists for the listing).
-->

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1><a href="{% url 'auctions:index' %}" style="color: black; text-decoration: none;">Auctions</h1></a>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create New Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'auctions:wins' %}">Purchases</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>{{ listing.title }}</h1>

    <!-- Add or Remove from Watchlist button -->
    {% if user.is_authenticated %}
        {% if in_watchlist %}
            <form action="{% url 'auctions:remove_from_watchlist' title=listing.title %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-light" name="remove_from_watchlist">Remove from Watchlist</button>
            </form>
        {% else %}
            <form action="{% url 'auctions:add_to_watchlist' title=listing.title %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="" name="add_to_watchlist">Add to Watchlist</button>
            </form>
        {% endif %}
    {% endif %}<br>
    

    <p>
        Description: {{ listing.description }}<br>
        Price: ${{ listing.current_bid.new_bid }}<br>
        Highest bidder: {{ listing.current_bid.user.username }}<br>
        <img src="{{ listing.imageURL }}" style="max-width: 450px;"><br>
        Seller: {{ listing.seller.username }}<br>
    </p>

    {% if is_active %}
        <form action="{% url 'auctions:new_bid' id=listing.id %}" method="POST">
            {% csrf_token %}
            <label>Bid: $</label>
            <input type="number" min="{{ listing.current_bid.new_bid }}" step="any" placeholder="{{ listing.current_bid.new_bid }}" name="bid" required>
            {% if user.is_authenticated %}
                <button type="submit" class="btn btn-success" name="submit_bid">Submit Bid</button>
            {% else %}
                <a href="{% url 'auctions:login' %}">Login to place bid</a>
            {% endif %}
        </form>
        {{ message }}<br>

        {% if userowner %}
            <br>
            <form action="{% url 'auctions:close_auction' id=listing.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" name="close_auction">Close Auction</button>
            </form>
        {% endif %}
    {% endif %}

    {% if won %}
        <p>You won this auction!</p>
    {% endif %}

    <!-- Display comments, comment box first if the user is logged in. -->
    {% if user.is_authenticated %}
        <form action="{% url 'auctions:comments' id=listing.id %}" method="POST">
            {% csrf_token %}
            <input type="text" name="new_comment" placeholder="Enter comment here">
            <button type="submit" class="btn btn-info">Comment</button>
        </form>
    {% endif %}
    <ul><br>
    {% for comment in comments %}
        <ul>
            {{ comment.user.username }}: {{ comment.comment }}
        </ul>
    {% endfor %}
    </ul>


{% endblock %}


<!--
    Listing Page: 
    Clicking on a listing should take users to a page specific to that listing. 
    On that page, users should be able to view all details about the listing, including the current price for the listing.
    
If the user is signed in, the user should be able to add the item to their “Watchlist.” 
If the item is already on the watchlist, the user should be able to remove it.
If the user is signed in, the user should be able to bid on the item. 
The bid must be at least as large as the starting bid, and must be greater than any other bids that have been placed (if any). 
If the bid doesn’t meet those criteria, the user should be presented with an error.
If the user is signed in and is the one who created the listing, 
the user should have the ability to “close” the auction from this page, 
which makes the highest bidder the winner of the auction and makes the listing no longer active.
If a user is signed in on a closed listing page, and the user has won that auction, the page should say so.
Users who are signed in should be able to add comments to the listing page. 
The listing page should display all comments that have been made on the listing.
-->

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h1>Watchlist</h1>

    {% if user.is_authenticated %}
        <ul>
            {% for listing in watchlistings %}
                <li>
                    <a href="{% url 'auctions:listing' title=listing.title %}">{{ listing.title }}</a><br>
                    ${{ listing.current_bid.new_bid }}
                </li><br>
            {% empty %}
            <p>
                No items in watchlist yet...
            </p>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

<!--
    Watchlist: 
    Users who are signed in should be able to visit a Watchlist page, 
    which should display all of the listings that a user has added to their watchlist. 
    Clicking on any of those listings should take the user to that listing’s page.
-->